# b
version: '3.1'

services:

  db:
    build: database/

  app_ai:
    build: main_ai/
    ports:
      - 5001:5001
    restart: always

  app_main:
    build: main_app/
    ports:
      - 5000:5000
    restart: always

  app_web:
    build: angular-project/

#volumes:
#  db:
#  app:
#  app_main: